### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by RamboRick** [Ozair0/Android-Sqlite-Implementation#1]
Hi Ozair,

I really admire your work. I wonder is this project under MIT license? If it is not,  is that Ok we can use it for internal tool/ supplement for research purposes? 

Thank you.
Gabriel

**Comment by RamboRick** [comment]
Or based on it to add some modifications for research purposes. Looking forward to your feedback. Thank you.

**Comment by Ozair0** [comment]
Hi RamboRick,

Thanks, yes you can use it for your research purposes no problem actually anyone can use it.

**Comment by RamboRick** [comment]
Thank you for your support for research ( code modification, paper presentation, and publication).

**Comment by RamboRick** [comment]
Hi Ozair, 

Can I know your full name so that we can cite your GitHub page in our research draft? If you don't want to use the full name, we can still use Ozair for it.  Please let me know if you see this comment.  Thank you.

**Comment by Ozair0** [comment]
Hi,

My full name is "Ozair Farahi".
